### ISSUE TITLE
[加入申请]

### ISSUE THREAD

**Issue by N55743** [LingmoOS/join-dev-team#1]
### 为什么想加入 LingmoOS Development Team？

我从lingmo系统诞生以来就一直关注着它，我一直想参与它的开发

### 介绍一下你自己

我会C++
我也可以测试以便发现其中的问题并提出改进意见

**Comment by chun-awa** [comment]
approved

**Comment by chun-awa** [comment]
please join the qq group

**Comment by chun-awa** [comment]
552152860
