### ISSUE TITLE
[加入申请]

### ISSUE THREAD

**Issue by TMXQWQ** [LingmoOS/join-dev-team#4]
### QQ号（可选）

273761857

### 为什么想加入 LingmoOS Development Team？

想更多了解灵墨os（加入开发？）

### 介绍一下你自己

# 简历

14岁，男，昆山

会一些汇编（x86/amd64，intel和at&t)，C(做过OS开发)，Cpp(入门)

**Comment by chun-awa** [comment]
approved, please join our qq group
