### ISSUE TITLE
[加入申请]

### ISSUE THREAD

**Issue by fawdlstty** [LingmoOS/join-dev-team#6]
### QQ号（可选）

1874293988

### 为什么想加入 LingmoOS Development Team？

持续关注，如果后续有rust相关的开发需求，我可以提供一定程度的助力

### 介绍一下你自己

假的语言律师，不专业的全栈开发者，职业帕鲁

**Comment by elysia-best** [comment]
如果您感兴趣的话，可以先加入我们的QQ群或者QQ频道
QQ 群：552152860 
点击链接加入腾讯频道【LingmoOS】：https://pd.qq.com/s/1kpaaq0cc
