### ISSUE TITLE
Join Request as a Translator

### ISSUE THREAD

**Issue by HachiroXD** [LingmoOS/join-dev-team#7]
### Why do you want to join the LingmoOS Development Team?

So, i'm using LingmoOS and want a german translation. so i want to apply

### Introduce yourself

I'm Hachiro, 18 years old and translated a few games so far

**Comment by elysia-best** [comment]
Hi Hachiro, the translation projects are currently hosted on Weblate. You can have a look at https://hosted.weblate.org/projects/lingmoos
